### ISSUE TITLE
No image file in latest 6.7 based release

### ISSUE THREAD

**Issue by juergenpf** [yuzibo/vf2-debian-image#4]
The assets just contain the sources, but no image.

**Comment by yuzibo** [comment]
thanks.

I just published v2 of 6.7 which has a very important [patch: set PLL0 rate to 1.5Ghz ](https://github.com/yuzibo/vf2-linux/tree/vf2-v6.7-v2) for performance.

Please try it:
https://github.com/yuzibo/vf2-debian-image/releases/tag/vf2-v6.7-v2

**Comment by yuzibo** [comment]
If any issue please reopen this.
